[notification.slack]
token = '{{ env "SLACK_TOKEN" }}'
channel = "#general"

[[target]]
name = "test endpoint"
url = "http://test_target:8080/"

[[target]]
name = "test endpoint ok"
url = "http://test_target:8080/ok"

[[target]]
name = "test endpoint error"
url = "http://test_target:8080/error"

[[target]]
name = "test endpoint timeout"
url = "http://test_target:8080/timeout"
